name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install yarn next react react-dom
          yarn add --dev typescript @types/react @types/node
      - name: Next build
        run: yarn build
      - name: Typescript
        run: yarn typescript-build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2